# Generated by Django 5.1.2 on 2024-10-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('cod_asig', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desc_asig', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombreD', models.CharField(max_length=30)),
                ('s_nombreD', models.CharField(blank=True, max_length=30)),
                ('p_apellidoD', models.CharField(max_length=30)),
                ('s_apellidoD', models.CharField(blank=True, max_length=30)),
                ('correoD', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('p_nombreE', models.CharField(max_length=30)),
                ('s_nombreE', models.CharField(blank=True, max_length=30)),
                ('p_apellidoE', models.CharField(max_length=30)),
                ('s_apellidoE', models.CharField(blank=True, max_length=30)),
                ('correoE', models.EmailField(max_length=254, unique=True)),
                ('secciones', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('cod_sala', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('desc_sede', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.horario')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('cod_seccion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_clases', models.JSONField()),
                ('clases_totales', models.IntegerField()),
                ('cod_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asignatura')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.docente')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sede'),
        ),
    ]
